<?php

namespace Cradle\Profiler;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Profiler_CallerTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var CallerTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CallerTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Profiler\CallerTrait::getCaller
     */
    public function testGetCaller()
    {
		$profile = $this->object->call1(1);
		print_r($profile);
    }

    /**
     * @covers Cradle\Profiler\CallerTrait::getCallee
     */
    public function testGetCallee()
    {
		$profile = $this->object->call4(1);
		print_r($profile);
    }
}

if(!class_exists('Cradle\Profiler\CallerTraitStub')) {
	class CallerTraitStub
	{
		use CallerTrait;
		
		public function call1($x)
		{
			$this->call2($x + 1);
		}
		
		public function call2($x)
		{
			$this->call3($x + 1);
		}
		
		public function call3($x)
		{
			return $this->getCaller();
		}
		
		public function call4($x)
		{
			$this->call5($x + 1);
		}
		
		public function call5($x)
		{
			$this->call6($x + 1);
		}
		
		public function call6($x)
		{
			return $this->getCallee();
		}
	}
}
