<?php

namespace Cradle\Profiler;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Profiler_LoggerException_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var LoggerException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoggerException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Profiler\LoggerException::forInvalidCallback
     */
    public function testForInvalidCallback()
    {
        $actual = null;
		
        try {
			throw LoggerException::forInvalidCallback();
		} catch(LoggerException $e) {
			$actual = $e->getMessage();
		}
		
		$expected = 'Invalid callback passed.';
		
		$this->assertEquals($expected, $actual);
    }
}
