<?php

namespace Cradle\Profiler;

use StdClass;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Profiler_LoggerTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var LoggerTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoggerTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Profiler\LoggerTrait::addLogger
     */
    public function testAddLogger()
    {
        $instance = $this->object->addLogger(function() {});
		$this->assertInstanceOf('Cradle\Profiler\LoggerTraitStub', $instance);
    }

    /**
     * @covers Cradle\Profiler\LoggerTrait::log
     */
    public function testLog()
    {
		$trigger = new StdClass();
		$trigger->success = null;
        $this->object->addLogger(function($trigger) {
			$trigger->success = true;
		})
		->log($trigger);


		$this->assertTrue($trigger->success);
    }
}

if(!class_exists('Cradle\Profiler\LoggerTraitStub')) {
	class LoggerTraitStub
	{
		use LoggerTrait;
	}
}
