<?php

namespace Cradle\Http;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:33.
 */
class Cradle_Http_Middleware_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var Middleware
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Middleware;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Http\Middleware::register
     */
    public function testRegister()
    {
        $instance = $this->object->register(function() {});
        $this->assertInstanceOf('Cradle\Http\Middleware', $instance);
    }

    /**
     * @covers Cradle\Http\Middleware::process
     */
    public function testProcess()
    {
        $this->assertTrue($this->object->process());
    }
}
