<?php

namespace Cradle\Data;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Cradle_Data_GeneratorTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var GeneratorTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GeneratorTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Data\GeneratorTrait::generator
     */
    public function testGenerator()
    {
        foreach($this->object->generator() as $i => $value);
		$this->assertEquals('bar', $i);
    }
}

if(!class_exists('Cradle\Data\GeneratorTraitStub')) {
	class GeneratorTraitStub
	{
		use GeneratorTrait;
		
		protected $data = array(
			'foo' => 'bar',
			'bar' => 'foo'
		);
	}
}
