language: php
php:
  - 5.6
install:
  - /home/travis/.phpenv/versions/5.6/bin/composer install
  - phpenv rehash
before_script:
  - mkdir -p build/logs
script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
