<?php

namespace Cradle\Framework\Flow;

use PHPUnit_Framework_TestCase;
use Cradle\Framework\Flow;
use Cradle\Http\Request;
use Cradle\Http\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Cradle_Framework_Flow_Log_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Framework\Flow\Log::report
     */
    public function testReport()
    {
        $callback = Flow::log()->report('something');
        $this->assertInstanceOf('Closure', $callback);

        $request = new Request;
        $response = new Response;

        $actual = $callback($request, $response);
        $this->assertNull($actual);
    }

    /**
     * @covers Cradle\Framework\Flow\Log::debug
     */
    public function testDebug()
    {
        $callback = Flow::log()->debug('something');
        $this->assertInstanceOf('Closure', $callback);

        $request = new Request;
        $response = new Response;

        ob_start();
        $actual = $callback($request, $response);
        ob_end_clean();
        $this->assertNull($actual);
    }

    /**
     * @covers Cradle\Framework\Flow\Log::register
     */
    public function testRegister()
    {
        $actual = Flow::log()->register(function() {});

        $this->assertNull($actual);
    }
}
