<?php

namespace Cradle\Helper;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Cradle_Helper_LoopTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var LoopTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoopTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Helper\LoopTrait::loop
     */
    public function testLoop()
    {
        $self = $this;
        $this->object->loop(function($i) use ($self) {
            $self->assertInstanceOf('Cradle\Helper\LoopTraitStub', $this);
            
            if ($i == 2) {
                return false;
            }
        });
    }
}

if(!class_exists('Cradle\Helper\LoopTraitStub')) {
	class LoopTraitStub
	{
		use LoopTrait;
	}
}
