<?php

namespace Cradle\Helper;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_Helper_SingletonTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var SingletonTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SingletonTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Helper\SingletonTrait::i
     */
    public function testI()
    {
        $instance1 = SingletonTraitStub::i();
		$this->assertInstanceOf('Cradle\Helper\SingletonTraitStub', $instance1);
		
		$instance2 = SingletonTraitStub::i();
		$this->assertTrue($instance1 === $instance2);
    }
}

if(!class_exists('Cradle\Helper\SingletonTraitStub')) {
	class SingletonTraitStub
	{
		use SingletonTrait;
	}
}
