<?php

namespace Cradle\Http\Response;

use PHPUnit_Framework_TestCase;

use Cradle\Http\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_Http_ResponseTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var ResponseTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResponseTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\ResponseTrait::getResponse
     */
    public function testGetResponse()
    {
        $instance = $this->object->getResponse();
        $this->assertInstanceOf('Cradle\Http\Response', $instance);
    }

    /**
     * covers Cradle\Http\ResponseTrait::setResponse
     */
    public function testSetResponse()
    {
        $instance = $this->object->setResponse(new Response);
        $this->assertInstanceOf('Cradle\Http\Response\ResponseTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Response\ResponseTraitStub')) {
    class ResponseTraitStub
    {
        use ResponseTrait;
    }
}
