<?php

namespace Cradle\Http\Response;

use PHPUnit_Framework_TestCase;
use Cradle\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class Cradle_Http_Response_StatusTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var StatusTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StatusTraitStub(array(
            'code' => 200,
            'headers' => array(
                'foo' => 'bar',
                'bar' => 'foo'
            )
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\Response\StatusTrait::getStatus
     */
    public function testGetStatus()
    {
        $code = $this->object->getStatus();
        $this->assertEquals(200, $code);
    }

    /**
     * covers Cradle\Http\Response\StatusTrait::setStatus
     */
    public function testSetStatus()
    {
        $instance = $this->object->setStatus(404, '404 Not Found');
        $this->assertInstanceOf('Cradle\Http\Response\StatusTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Request\StatusTraitStub')) {
    class StatusTraitStub extends Registry
    {
        use StatusTrait;
    }
}
