<?php

namespace Cradle\Http\Request;

use PHPUnit_Framework_TestCase;
use Cradle\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class Cradle_Http_Request_CookieTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var CookieTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CookieTraitStub;
        
        $this->object->set('cookie', array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\Request\CookieTrait::getCookies
     */
    public function testGetCookies()
    {
        $this->assertEquals('bar', $this->object->getCookies('foo'));
    }

    /**
     * covers Cradle\Http\Request\CookieTrait::hasCookies
     */
    public function testHasCookies()
    {
        $this->assertTrue($this->object->hasCookies('foo'));
        $this->assertFalse($this->object->hasCookies('zoo'));
    }

    /**
     * covers Cradle\Http\Request\CookieTrait::removeCookies
     */
    public function testRemoveCookies()
    {
        $this->object->removeCookies('foo');
        $this->assertFalse($this->object->hasCookies('foo'));
    }

    /**
     * covers Cradle\Http\Request\CookieTrait::setCookies
     */
    public function testSetCookies()
    {
        $instance = $this->object->setCookies(array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
        
        $this->assertInstanceOf('Cradle\Http\Request\CookieTraitStub', $instance);
		
		$instance = $this->object->setCookies('zoo');
        $this->assertInstanceOf('Cradle\Http\Request\CookieTraitStub', $instance);

        $instance = $this->object->setCookies('zoo', 'foo', 'bar');
        $this->assertInstanceOf('Cradle\Http\Request\CookieTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Request\CookieTraitStub')) {
    class CookieTraitStub extends Registry
    {
        use CookieTrait;
    }
}
