<?php

namespace Cradle\Http\Request;

use PHPUnit_Framework_TestCase;
use Cradle\Http\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_Http_RequestTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var RequestTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RequestTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\RequestTrait::getRequest
     */
    public function testGetRequest()
    {
        $instance = $this->object->getRequest();
        $this->assertInstanceOf('Cradle\Http\Request', $instance);
    }

    /**
     * covers Cradle\Http\RequestTrait::setRequest
     */
    public function testSetRequest()
    {
        $instance = $this->object->setRequest(new Request);
        $this->assertInstanceOf('Cradle\Http\Request\RequestTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Request\RequestTraitStub')) {
    class RequestTraitStub
    {
        use RequestTrait;
    }
}
