<?php

namespace Cradle\Http\Request;

use PHPUnit_Framework_TestCase;
use Cradle\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class Cradle_Http_Request_RouteTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var RouteTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RouteTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\Request\RouteTrait::getRoute
     */
    public function testGetRoute()
    {
        $this->object->set('route', array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
        
        $this->assertEquals('bar', $this->object->getRoute('foo'));
    }

    /**
     * covers Cradle\Http\Request\RouteTrait::getParameters
     */
    public function testGetParameters()
    {
        $this->object->set('route', array(
            'foo' => 'bar',
            'parameters' => array('foo' => 'bar')
        ));
        
        $this->assertEquals('bar', $this->object->getParameters('foo'));
    }

    /**
     * covers Cradle\Http\Request\RouteTrait::getVariables
     */
    public function testGetVariables()
    {
        $this->object->set('route', array(
            'foo' => 'bar',
            'variables' => array('foo', 'bar')
        ));
        
        $this->assertEquals('bar', $this->object->getVariables(1));
    }

    /**
     * covers Cradle\Http\Request\RouteTrait::setRoute
     */
    public function testSetRoute()
    {
        $instance = $this->object->setRoute(array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
        
        $this->assertInstanceOf('Cradle\Http\Request\RouteTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Request\RouteTraitStub')) {
    class RouteTraitStub extends Registry
    {
        use RouteTrait;
    }
}
