<?php

namespace Cradle\Http\Request;

use PHPUnit_Framework_TestCase;
use Cradle\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class Cradle_Http_Request_StageTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var StageTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StageTraitStub;
        
        $this->object->set('stage', array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * covers Cradle\Http\Request\StageTrait::getStage
     */
    public function testGetStage()
    {    
        $this->assertEquals('bar', $this->object->getStage('foo'));
    }

    /**
     * covers Cradle\Http\Request\StageTrait::hasStage
     */
    public function testHasStage()
    {    
        $this->assertTrue($this->object->hasStage('foo'));
        $this->assertFalse($this->object->hasStage('zoo'));
    }

    /**
     * covers Cradle\Http\Request\StageTrait::removeStage
     */
    public function testRemoveStage()
    {
        $this->object->removeStage('foo');
        $this->assertFalse($this->object->hasStage('foo'));
    }

    /**
     * covers Cradle\Http\Request\StageTrait::setSoftStage
     */
    public function testSetSoftStage()
    {
        $instance = $this->object->setSoftStage(array(
            'foo' => 'bar',
            'bar' => 'zoo'
        ));
        
        $this->assertInstanceOf('Cradle\Http\Request\StageTraitStub', $instance);
		$this->assertEquals('foo', $this->object->getStage('bar'));
    }

    /**
     * covers Cradle\Http\Request\StageTrait::setStage
     */
    public function testSetStage()
    {
        $instance = $this->object->setStage(array(
            'foo' => 'bar',
            'bar' => 'foo'
        ));
        
        $this->assertInstanceOf('Cradle\Http\Request\StageTraitStub', $instance);
		
		$instance = $this->object->setStage();
        $this->assertInstanceOf('Cradle\Http\Request\StageTraitStub', $instance);
		
		$instance = $this->object->setStage('zoo');
        $this->assertInstanceOf('Cradle\Http\Request\StageTraitStub', $instance);

        $instance = $this->object->setStage('zoo', 'foo', 'bar');
        $this->assertInstanceOf('Cradle\Http\Request\StageTraitStub', $instance);
    }
}

if(!class_exists('Cradle\Http\Request\StageTraitStub')) {
    class StageTraitStub extends Registry
    {
        use StageTrait;
    }
}
