<?php

namespace Cradle\Event;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Cradle_Event_EventException_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var EventException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EventException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Event\EventException::forInvalidCallback
     */
    public function testForInvalidCallback()
    {
        $actual = null;
		
        try {
			throw EventException::forInvalidCallback();
		} catch(EventException $e) {
			$actual = $e->getMessage();
		}
		
		$expected = 'Invalid callback passed.';
		
		$this->assertEquals($expected, $actual);
    }
}
